# Демонстрирует чтение из текстового файла
text_file = open("read_it.txt", "w", encoding = 'utf-8')
text_file.write("Cтрока 1\n")
text_file.write("Это строка номер 2\n")
text_file.write("Этой строке достался номер 3\n")
text_file.close()
print("\nЧитаю файл посимвольно: ")
text_file = open("read_it.txt", "r")
print(text_file.read(1))
print(text_file.read(5))
text_file.close()
print()
text_file = open("read_it.txt", "r", encoding = 'utf-8')
print(text_file.read())
text_file.close()
print("Читаю одну строку посимвольно: ")
text_file = open("read_it.txt", "r", encoding = 'utf-8')
print(text_file.readline(1))
print(text_file.readline(5))
text_file.close()
print()
text_file = open("read_it.txt", "r", encoding = 'utf-8')
print(text_file.readline())
print(text_file.readline())
print(text_file.readline())
text_file.close()
text_file = open("read_it.txt", "r", encoding = 'utf-8')
lines = text_file.readlines()
print(lines)
print(len(lines))
for line in lines:
    print(line)
text_file.close()
text_file = open("read_it.txt", "r", encoding = 'utf-8')
for line in text_file:
    print(line)
input("\nPress Enter to exit")

